services:

  postgres:
    image: postgres:18-bookworm
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./app.log:/app/app.log
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vietio-network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: deploy/backend/Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app.log:/app/app.log
    restart: always
    networks:
      - vietio-network

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
    restart: always
    networks:
      - vietio-network

  frontend-builder:
    container_name: frontend-builder
    build:
      context: ../vietio-ui
      dockerfile: ./Dockerfile
    volumes:
      - frontend_build:/app/build
    command: npm run build
    restart: "no"
    networks:
      - vietio-network

volumes:
  postgres_data:
  frontend_build:

networks:
  vietio-network:
    driver: bridge
