services:

  postgres:
    restart: always

  backend:
    restart: always

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
    restart: always
    networks:
      - vietio-network

  frontend-builder:
    build:
      context: ../vietio-ui
      dockerfile: ./Dockerfile
    volumes:
      - frontend_build:/app/build
    command: npm run build
    restart: "no"
    networks:
      - vietio-network

volumes:
  frontend_build: